name: lms
adopt-info: lms
summary: Intel(R) AMT Local Manageability Service
description: Intel(R) Active Management Technology Local Manageability Service
 allows applications to access
 the Intel Active Management Technology (AMT) firmware
 via the Intel Management Engine Interface (MEI).

grade: stable
confinement: strict
base: core18
architectures:
  - build-on: amd64

apps:
  lms:
    command: lms
    daemon: simple
    plugs:
        - network-observe
        - network-bind
        - shutdown
        - network
        - hardware-observe
        - network-manager
        - network-control
        - intel-mei
    slots:
        - dbus-svc

slots:
  dbus-svc:
    interface: dbus
    bus: system
    name: com.intel.amt.lms

parts:
  metee:
    plugin: cmake
    source: https://github.com/intel/metee.git
    # MeTee 3.0.1
    source-commit: 9b9cfca7a4597772912c565fae285c27d99ad017
    build-packages:
      - g++
      - make
  lms:
    plugin: cmake
    #configflags:
    #  - -DCMAKE_BUILD_TYPE=Debug
    source: .
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(cat VERSION)
    build-packages:
      - g++
      - make
      - libace-dev
      - libxerces-c-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - python3
      - libxml2-dev
      - network-manager-dev
      - xsltproc
      - docbook-xsl
      - libcurl4-openssl-dev
    stage-packages:
      - libace-6.4.5
      - libnl-3-200
      - libnl-route-3-200
      - libcurl4
      - libxerces-c3.2
      - libxml2
